### ISSUE TITLE
equiptitle doesnt seem to give feedback

### ISSUE THREAD

**Issue by crazygmr101** [aoi-bot/Aoi#23]
```
ERROR:aiosqlite:returning exception no such column: guild
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiosqlite/core.py", line 95, in run
    result = function()
sqlite3.OperationalError: no such column: guild
Ignoring exception in command equiptitle:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/crazygmr101/aoi/cogs/user/global_shop.py", line 99, in equiptitle
    await self.bot.db.equip_title(ctx.author, num)
  File "/home/crazygmr101/aoi/aoi/database.py", line 364, in equip_title
    await self.cache_flush()
  File "/home/crazygmr101/aoi/aoi/database.py", line 257, in cache_flush
    await self.db.execute("DELETE FROM guild_shop WHERE guild=?", (guild,))
  File "/usr/local/lib/python3.7/site-packages/aiosqlite/core.py", line 160, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/usr/local/lib/python3.7/site-packages/aiosqlite/core.py", line 109, in _execute
    return await future
  File "/usr/local/lib/python3.7/site-packages/aiosqlite/core.py", line 95, in run
    result = function()
sqlite3.OperationalError: no such column: guild
```

**Comment by crazygmr101** [comment]
database issue
